name: Build

on: push

env:
  PIXLET_REPO: tidbyt/pixlet
  PIXLET_VERSION: v0.33.4

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/gabe565/pixlet
          tags: |
            type=raw,priority=1000,value=latest,enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{version}},value=${{ env.PIXLET_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.PIXLET_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{major}},value=${{ env.PIXLET_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=ref,event=branch
          labels: |
            org.opencontainers.image.title=Pixlet
            maintainer=gabe565
            org.opencontainers.image.vendor=gabe565
            org.opencontainers.image.description=Build apps for pixel-based displays
            org.opencontainers.image.source=https://github.com/${{ env.PIXLET_REPO }}
            org.opencontainers.image.version=${{ env.PIXLET_VERSION }}
            org.opencontainers.image.licenses=Apache-2.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PIXLET_REPO=${{ env.PIXLET_REPO }}
            PIXLET_VERSION=${{ env.PIXLET_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
