name: Build

on: push

env:
  PIXLET_REPO: tidbyt/pixlet
  PIXLET_VERSION: v0.34.0

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ghcr.io/gabe565/pixlet
          tags: |
            type=raw,priority=1000,value=latest,enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{version}},value=${{ env.PIXLET_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.PIXLET_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=semver,pattern={{major}},value=${{ env.PIXLET_VERSION }},enable=${{ github.ref_name == 'main' }}
            type=ref,event=branch
          labels: |
            org.opencontainers.image.title=Pixlet
            maintainer=gabe565
            org.opencontainers.image.vendor=gabe565
            org.opencontainers.image.description=Build apps for pixel-based displays
            org.opencontainers.image.source=https://github.com/${{ env.PIXLET_REPO }}
            org.opencontainers.image.version=${{ env.PIXLET_VERSION }}
            org.opencontainers.image.licenses=Apache-2.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PIXLET_REPO=${{ env.PIXLET_REPO }}
            PIXLET_VERSION=${{ env.PIXLET_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
